### PR TITLE
fix external media access

### PR DESCRIPTION
**Pull request by MarcusZuber**
This seams to fix https://github.com/nibuen/SpaceAlertMissionGenerator/issues/48 at least up to Android 10.

### CODE REVIEW

**Comment by nibuen** [comment]
thanks for this @MarcusZuber !  Since you refactored to kotlin can you help point to line that fixes it so I can help validate?

**Comment by nibuen** [comment]
pretty sure you are missing permission requests still?  This part of the code base is really ugly anyways I will help cleanup and merge the rest, thanks again for help

**Comment by MarcusZuber** [comment]
The only thing I changed (beside changing to kotlin and then doing some small adjustments due to this) was to change how the `File` object was created.

I changed this
```
File dir = new File(Environment.getExternalStorageDirectory().getAbsolutePath() + "/com.boarbeard");
FileOutputStream(new File(dir.getAbsolutePath() + "/readme.txt"));

```
to
 
`FileOutputStream(File(context.getExternalFilesDir(null), "readme.txt"))` that, which seams the new implementation in `java.io.File`,. For the other files and the reading of the file list I did it similar.

The permissions are still confusing me a little bit. The app newer asks about the storage permissions, and it even works, when they are never granted or removed. Probably, this is because only the app-related external storage (/sdcard/Android/data/com.boarbeard) is used?

**Comment by nibuen** [comment]
> The only thing I changed (beside changing to kotlin and then doing some small adjustments due to this) was to change how the `File` object was created.
> 
> I changed this
> 
> ```
> File dir = new File(Environment.getExternalStorageDirectory().getAbsolutePath() + "/com.boarbeard");
> FileOutputStream(new File(dir.getAbsolutePath() + "/readme.txt"));
> ```
> 
> to
> 
> `FileOutputStream(File(context.getExternalFilesDir(null), "readme.txt"))` that, which seams the new implementation in `java.io.File`,. For the other files and the reading of the file list I did it similar.
> 
> The permissions are still confusing me a little bit. The app newer asks about the storage permissions, and it even works, when they are never granted or removed. Probably, this is because only the app-related external storage (/sdcard/Android/data/com.boarbeard) is used?

Thanks, I checked it is no longer required for checking permissions on external directory, so I think we are good and I will just make this more friendly around it.

**Pull request merged**
